name: Tests

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: node --version && npm install

      - name: Run tests
        run: npm test
